In [44]:
from nibabel import load
from pandas import Series, DataFrame, read_csv
from os import path
from glob import glob
from datetime import date

In [61]:
timepoint = input('Which timepoint are you checking? Enter "Newborn" or "6month":  ')
fp = '/Volumes/iang/active/BABIES/BABIES_diffusion/subjsDir/'+ timepoint
sublist = Series(glob(fp + '/*-*-T*')).str.replace(fp+'/', '')
subs = sublist.sort_values()

Which timepoint are you checking? Enter "Newborn" or "6month":  Newborn

4     1005-L-T2
9     1010-L-T2
2     1011-L-T2
14    1017-L-T2
3     1020-L-T2
13    1023-L-T2
12    1027-L-T2
5     1028-L-T2
11    1033-L-T2
15    1036-L-T2
10    1037-L-T2
1     1038-L-T2
0     1042-L-T2
8     1043-L-T2
7     1053-L-T2
6     1057-L-T2
dtype: object

In [62]:
final = DataFrame(columns = ['ID', '#bvals', '#bvecs', 'NIFTI length'])
for sub in subs:
    if path.exists(fp + '/'+sub+'/raw/DTI_pe0_ms103.bval'):
        bval = read_csv(fp + '/' + sub +'/raw/DTI_pe0_ms103.bval', sep = ' ', header = None)
        bval1 = len(bval.columns)
    else:
        print('Bval not found for {}'.format(sub))
    if path.exists(fp + '/'+sub+'/raw/DTI_pe0_ms103.bvec'):
        bvec = read_csv(fp + '/' + sub +'/raw/DTI_pe0_ms103.bvec', sep = ' ', header = None)
        bvec1 = len(bvec.columns)
    else:
        print('Bvec not found for {}'.format(sub))
    if path.exists(fp + '/'+sub+'/raw/DTI_pe0_ms103.bvec'):
        nii = load(fp + '/' + sub +'/raw/DTI_pe0_ms103.nii.gz')
        nii1 = nii.shape[3]
    else:
        print('Nifti not found for {}'.format(sub))
    data = Series([sub, bval1, bvec1, nii1], index = ['ID', '#bvals', '#bvecs', 'NIFTI length'])
    final = final.append(data, ignore_index = True)

Bval not found for 1020-L-T2
Bvec not found for 1020-L-T2
Nifti not found for 1020-L-T2
Bval not found for 1023-L-T2
Bvec not found for 1023-L-T2
Nifti not found for 1023-L-T2
Bval not found for 1027-L-T2
Bvec not found for 1027-L-T2
Nifti not found for 1027-L-T2
Bval not found for 1033-L-T2
Bvec not found for 1033-L-T2
Nifti not found for 1033-L-T2
Bval not found for 1036-L-T2
Bvec not found for 1036-L-T2
Nifti not found for 1036-L-T2
Bval not found for 1037-L-T2
Bvec not found for 1037-L-T2
Nifti not found for 1037-L-T2

In [63]:
final

           ID #bvals #bvecs NIFTI length
0   1005-L-T2    104    104          104
1   1010-L-T2    104    104          104
2   1011-L-T2     16     16           16
3   1017-L-T2    104    104          104
4   1020-L-T2    104    104          104
5   1023-L-T2    104    104          104
6   1027-L-T2    104    104          104
7   1028-L-T2    104    104          104
8   1033-L-T2    104    104          104
9   1036-L-T2    104    104          104
10  1037-L-T2    104    104          104
11  1038-L-T2    104    104          105
12  1042-L-T2    104    104          104
13  1043-L-T2    105    105          105
14  1053-L-T2    105    105          105
15  1057-L-T2    104    104          105

In [37]:
today = str(date.today())
final.to_csv(fp+'/'+timepoint+'_File_QC_Report_'+today+'.csv')