In [4]:
import pandas as pd
import os
from nipype.interfaces.fsl import MotionOutliers
import glob

In [10]:
sixmonth = '/Users/myelin/Desktop/BABIES_motionprac'
newborn = 'Path to Newborn Data'

In [34]:
sublist = []
ids = []
def get_subs(timepoint):
    subpaths = glob.glob(timepoint + '/*-*-*')
    for sub in subpaths:
        sub1 = sub.replace(timepoint+'/', '')
        ids.append(sub1)
        sub2 = sub1.replace('-C-T1', '').replace('-L-T2', '').replace('-L-T3', '')
        sublist.append(sub2)
    return print('All subs appended extracted for timepoint')
get_subs(sixmonth)

All subs appended extracted for timepoint

In [43]:
def get_mot(sub):
    mot = MotionOutliers(in_file = timepoint +'/'+ sub + '/dwi/DTI_unwarped.nii.gz',
                        metric = metricv,
                        threshold = 0.25,
                        out_metric_values = timepoint + '/'+ sub + '/{}_motion_summary_{}.txt'.format(sub, metricv),
                        out_metric_plot = timepoint + '/'+sub +'/{}_motion_plot_{}.png'.format(sub, metricv),
                        no_motion_correction = False)
    return mot.run()

In [44]:
metricv = 'dvars'
timepoint = sixmonth
for sub in ids:
    get_mot(sub)

In [48]:
for sub in ['124-C-T1']:
    fd = pd.read_csv(timepoint + '/'+ sub + '/{}_motion_summary_fdrms.txt'.format(sub, metricv), header = None)
    dvars = pd.read_csv(timepoint + '/'+ sub + '/{}_motion_summary_dvars.txt'.format(sub, metricv), header = None)

dvar_math = fd - dvars
dvar_math

               0
0       0.000000
1    -618.713790
2   -4632.719090
3    -265.811810
4   -1481.074260
5   -1505.023440
6    -224.632750
7   -1465.320178
8   -1473.723351
9   -1562.954104
10  -1538.972382
11   -258.785050
12  -1613.601590
13  -1588.165840
14   -211.675240
15  -4679.217620
16  -4661.064910
17  -1604.482530
18  -1612.267510
19   -268.109940
20  -1585.573000
21  -1559.727030
22   -260.625582
23  -1512.557066
24  -1546.462841
25  -4680.884320
26  -4634.609640
27   -252.928680
28  -1560.297520
29  -1564.372420
..           ...
75  -1548.060830
76  -1546.823910
77   -241.164897
78  -1452.282950
79  -1478.395820
80   -202.569540
81  -1532.983550
82  -1538.754880
83  -4634.163630
84  -4652.269310
85   -255.508046
86  -1574.212629
87  -1572.369940
88   -253.374327
89  -1460.382530
90  -1460.221030
91  -1528.330870
92  -1563.377617
93   -248.072706
94  -4635.168220
95  -4649.712900
96   -255.712111
97  -1514.829342
98  -1500.483160
99  -1437.302320
100 -1450.986630
101  -254.322600
102 -1545.159734
103 -1503.023200
104 -4636.190950

[105 rows x 1 columns]